### ISSUE TITLE
Add a MonitoringStreamsTask implementation that emits metrics to MetricRegistry

### ISSUE THREAD

**Issue by ebrard** [streamthoughts/azkarra-streams#113]
MonitoringStreamsInterceptor  along with the MonitoringStreamsTask class are meant to push the stream state into a topic, although convenient having an implementation that can emit a metric into the MetricRegistry would make it possible to have direct integration with monitoring systems like DataDog that supports alerting.

**Comment by fhussonnois** [comment]
Hi @ebrard, thank you very much for the idea. I think you are mainly interessting by having the partition-lag-info exposed though the MetricRegistry, isn't ?

The `MonitoringStreamsInterceptor` class cannot be linked directly to the `MetricRegistry` .

Maybe we can introduce a new interface: `MonitoringStreamListerner`.apply([KafkaStreamsMetadata](https://github.com/streamthoughts/azkarra-streams/blob/master/azkarra-runtime/src/main/java/io/streamthoughts/azkarra/runtime/interceptors/monitoring/KafkaStreamsMetadata.java)) that will be invoked each time a event is emitted by the `MonitoringStreamsTask` class.

Then, the azkarra-metrics can provide an implementation to register metrics to the registry.

**Comment by ebrard** [comment]
Well actually I have mostly interested in the `state` of the stream. We push this information as a heartbeat kind of metric to Datadog and monitor its value over time. We currently do that with a `StateListerner` implementation.

**Comment by ebrard** [comment]
@fhussonnois So actually we are considering streamthoughts and it was one of the last blocker. For the moment, I just implemented an alternative MonitoringStreamsInterceptor `class` with a modified `MonitoringStreamsTask` that basically push to Datadog instead of a Kafka topic. That works fine but it would be way more convenient if I just had to implement an interface as you suggested. Do you have any further thoughts or is there already something planned for the next version 0.9.0 I guess?

**Comment by fhussonnois** [comment]
Hi @ebrard, Yes the new interface will be added in Azkarra 0.9.0. that should be released this week. Nice to hear that you are considering to use Azkarra  ;-)

**Comment by ebrard** [comment]
Ok, let me close this issue then.
