### ISSUE TITLE
Configurable topology name with auto component scan

### ISSUE THREAD

**Issue by ebrard** [streamthoughts/azkarra-streams#118]
When using the AzkarraStreamsApplication annotation, is there a way to override the name of a topology for example with a @Name annotation? Or somehow extended the existing annotation `TopologyInfo` ?

**Comment by fhussonnois** [comment]
Hi @ebrard, you should be able to annotate you Topology with `@Named` to override its name.

**Comment by ebrard** [comment]
Thx
