### ISSUE TITLE
How to handle exception thrown during Kafka Streams execution?

### ISSUE THREAD

**Issue by marcospassos** [streamthoughts/azkarra-streams#24]
First of all, thank you for the work on this fantastic project.

I'd love to read [this FAQ entry ](https://streamthoughts.github.io/azkarra-streams/docs/developer-guide/error-management/) , but it's unfinished. I have a stream application that writes to Google BigTable using GRPC and needs to produce a new message only when the record has been successfully flushed. 

Does the framework provide any way to recover the stream from an uncaught error during the message processing, such as a connection error?

**Comment by fhussonnois** [comment]
Hi @marcospassos, sorry for the missing documentation. Error handling should be improved in the following versions.

In Kafka Streams, you can handle errors by configuring either a `default.deserialization.exception.handler` or a `default.production.exception.handler.`

However, Kafka Streams does not provide any integrated mechanism to manage processing exceptions that can be thrown by a streams operator (e.g Map, Filter). So it's up to you catch exceptions thrown by your Map operation. 

Azkarra has a [DeadLetterTopicExceptionHandler](https://github.com/streamthoughts/azkarra-streams/blob/master/azkarra-commons/src/main/java/io/streamsthoughts/azkarra/commons/error/DeadLetterTopicExceptionHandler.java) which is provided by the azkarra-commons module.

I hope this will answer your question

**Comment by marcospassos** [comment]
Thank you!
