### ISSUE TITLE
How to specify the application ID?

### ISSUE THREAD

**Issue by marcospassos** [streamthoughts/azkarra-streams#34]
We'd like to always use the same application ID regardless of the current version to ensure the application will not start processing the messages from the beginning. Is there a configuration for it?

**Comment by fhussonnois** [comment]
Hi @marcospassos , Azkarra will generate an application ID if no property `application.id` is already configured.
So you can simply add the configuration into your` application.conf` file: 

```hocon
azkarra {
 context {
   streams {
     application.id: "you.app.id"
   } 
 }
}
```

Please, close this issue if your problem is resolved.

Thanks.

**Comment by marcospassos** [comment]
Thank you!
