### ISSUE TITLE
Health status marked as UNKNOWN upon crash instead of DOWN

### ISSUE THREAD

**Issue by Fryuni** [streamthoughts/azkarra-streams#54]
The `/health` endpoint returns status "UNKNOWN" at the body and status code 200 when a uncaught exception happen in the application.  
The application crashes and the stacktrace is logged correctly, but since the healthcheck still returns something that is not an error, it is never captured by any orchestration.

This became a problem in our cluster. For example, when a Kafka node fails, all threads with partitions that had it as the leader throws an exception and crashes, which brings the whole app down. This is the intended behaviour for Kafka Streams, the application crashes and you can restart it, manually or automatically.  

#### What we expected
The health-check endpoint would mark a crashed application as being unhealthy, Kubernetes would restart the pod and the application would connect to the new leader.

#### What actually happened
The health-check endpoint changed to unknown and consider that a "OK". Therefore Kubernetes, logically, did nothing.

---
Is that an intended behaviour? Currently, the only way for us to have applications auto-healing is to inject a bash script to parse the response consider the "UNKNOWN" from the body as unhealthy. To me it seems to defeat the purpose of having a health-check endpoint, if you need to use a bash script you can just check if the process is running.

**Comment by fhussonnois** [comment]
Hi @Fryuni, thanks for reporting this issue. Which version of Azkarra are you currently running ? I will fix this soon.

**Comment by Fryuni** [comment]
We are using v0.5.0. We can try with v0.6.0 if there was any changes that might affect this.

**Comment by Fryuni** [comment]
Hi @fhussonnois , do you have an idea of what is the problem and/or an estimate ETA? Just so I know if I can push this down on my sprint or if I should make a more decent script to send to production while you are on it 😄

**Comment by fhussonnois** [comment]
@Fryuni could you give the version of Apache Kafka and Kafka Streams you are using ? I didn't succeed to reproduce StreamThread failure when a leader election is triggered. 

Also, can you confirm to me that the state your Kafka Streams instance is equal to NOT_RUNNING when you observe the behaviour ? A fix should be available this week.

**Comment by Fryuni** [comment]
The cause of the crash in my example might be exclusive to our scenario (how we route our connections to kafka), but the same happens with any exception on the code, to reproduce you can create an app that always throw an exception.

We are using Kafka and Kafka Streams version 2.4.0

**Comment by Fryuni** [comment]
And yes, on the logs the state goes RUNNING -> PENDING_SHUTDOWN -> NOT_RUNNING right after the exception is logged

**Comment by fhussonnois** [comment]
This issue has been fix in Azkarra v0.6.1. I strongly recommand to you to upgrade.

**Comment by Fryuni** [comment]
Thaaanks @fhussonnois !!
