### ISSUE TITLE
DefaultAzkarraContext should throw InvalidStreamsEnvironmentException when an environment doesn't exists

### ISSUE THREAD

**Issue by fhussonnois** [streamthoughts/azkarra-streams#60]
Currently the class `DefaultAzkarraContext``will throw an `AzkarraContextException` when a topology is add to a unknown StreamsExecutionEnvironment (i.e : `DefaultAzkarraContext#checkIfEnvironmentExists`)

This exception can be specialized by adding a new class `InvalidStreamsEnvironmentException` that extends `AzkarraContextException`.

Javadoc for method `DefaultAzkarraContext#start` and `DefaultAzkarraContext#addTopology` should be updated also.

**Comment by arujit** [comment]
Hey @fhussonnois can I pick up this task? I am new to the opensource world but have a fine understanding on Kafka and Kafka streams. Was browsing through and it's a small thing to contibute but a fine startinng point for me, I guess.

**Comment by fhussonnois** [comment]
Hi @arujit , yes you can pick up this issue and submit a PR that I will review.

Do not hesitate to ask for any help.
Thank you very much for your help.

**Comment by arujit** [comment]
Hi @fhussonnois. Please review the PR. Also could not find the reason why Javadoc for method `DefaultAzkarraContext#start` and `DefaultAzkarraContext#addTopology` should be updated as part of the issue. Can you please give more context around this.
