### ISSUE TITLE
Collecting custom metrics

### ISSUE THREAD

**Issue by marcospassos** [streamthoughts/azkarra-streams#62]
Although Azkarras provides support for exporting streams application metrics to Prometheus, I couldn't find any mention in the docs about how to collect domain-specific metrics.

Is there any way to track custom metrics using the same infrastructure the Azkarras already provides?

**Comment by fhussonnois** [comment]
Hi @marcospassos, currently Azkarra doesn't provide built-in mecanism to export custom metrics; but I'm currently looking to the best way to integration [micrometer](https://micrometer.io/) to Azkarra.

If you are looking to add metrics into your KafkaStreams Topology this can be done using the [low-level processor API](https://docs.confluent.io/current/streams/monitoring.html#adding-your-own-metrics). All metrics defined using the Kafka Streams API will be exposed through the Azkarra /streams/:id/metrics endpoint.

**Comment by fhussonnois** [comment]
Hi @marcospassos can we close that issue ? Does the Micrometer integration which has beed added in Azkarra 0.7.0 solve your need ? 

Thanks.
